name: build-windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >
            git
            make
            mingw-w64-i686-gcc

      - name: Build
        shell: msys2 {0}
        run: |
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: hev-socks5-tunnel-win32
          path: bin/*.exe
